<a href="https://colab.research.google.com/github/Bhavya-1209/Marks-Adding/blob/main/Marks_Adding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **BY IMPORTING CSV**

In [31]:
import csv

file=open('Marks.csv','r')
csvreader=csv.reader(file)
header=next(csvreader) #extract the header

totalMarks={}
for row in csvreader:
  x=row[0]
  if x in totalMarks:
    totalMarks[x]=totalMarks[x]+int(row[1])
  else:
    totalMarks[x]=int(row[1])
print(totalMarks)

{'102003542': 4, '102003640': 5, '102003725': 5, '102003307': 4, '102003458': 5, '102003643': 5, '102017134': 4, '102003207': 4, '102003315': 5, '102003362': 4, '102003135': 4, '102003650': 5, '102003675': 5, '102003671': 4, '102003374': 3, '102017034': 5, '102003306': 5, '102003141': 5, '102003592': 5, '102003478': 5, '102017030': 2, '102016114': 4, '102003152': 3, '102017101': 5, '102003098': 5, '102003633': 3, '102003132': 5, '102066004': 5, '102003466': 5, '102017188': 5, '102003413': 4, '102016094': 4, '102017190': 5, '102017121': 4, '102003118': 5, '102003681': 5, '102183051': 4, '102017016': 4, '102003649': 5, '102003448': 4, '102003421': 2, '102017152': 5, '102053044': 3, '102003169': 5, '102016049': 5, '102017081': 5, '102053017': 4, '102003299': 4, '102017096': 5, '102003161': 5, '102003109': 5, '102003313': 5, '102003138': 5, '102017078': 5, '102003445': 5, '102003553': 5, '102017186': 5, '102003527': 5, '102003407': 5, '102017100': 5, '102003674': 4, '102183047': 5, '102003160': 5, '102003049': 5, '102003701': 4, '102017159': 4, '102067010': 5, '102003112': 5, '102003522': 5, '102017067': 5, '102003069': 4, '102053019': 2, '102016060': 5, '102003384': 3, '102017169': 5, '102017043': 4, '102017133': 4, '102183052': 5, '102003732': 5, '102003562': 4, '102003235': 5, '102003290': 4, '102003746': 5, '102003694': 5, '102003586': 5, '102003710': 5, '102003439': 5, '102016116': 5, '102003127': 5, '102017084': 5, '102067004': 5, '102016011': 5, '102017005': 4, '102016099': 4, '102053036': 5, '102003441': 3, '102003106': 5, '102003129': 5, '102003346': 4, '102003647': 5, '102003274': 4, '102003090': 2, '102183044': 5, '102003711': 5, '102003624': 5, '102003656': 3, '102017029': 5, '102016082': 3, '102003238': 5, '102003002': 5, '102003614': 5, '102003459': 5, '102003099': 5, '102003760': 3, '102017036': 5, '102003312': 5, '102017143': 5, '102016102': 5, '102067009': 5, '102003505': 5, '102003206': 5, '102003409': 4, '102003738': 4, '102017040': 5, '102003440': 5, '102003688': 5, '102017122': 5, '102017064': 5, '102067007': 5, '102003041': 2, '102017147': 5, '102003356': 4, '102003166': 5, '102017074': 4, '102003707': 5, '102003228': 5, '102003366': 4, '102003165': 3, '102003423': 4, '102053018': 2, '102053032': 4, '102003631': 5, '102003475': 5, '102003663': 3, '102003716': 5, '102017025': 5, '102003333': 5, '102017191': 5, '102003364': 4, '102003101': 4, '102017132': 4, '102017059': 5, '102003405': 3, '102003702': 4, '102003257': 5, '102003472': 5, '102003113': 5, '102053028': 5, '102003628': 5, '102183056': 4, '102003451': 5, '102003578': 5, '102053013': 1, '102003334': 5, '102053012': 3, '102017024': 5, '102003463': 4, '102017045': 5, '102017189': 5, '102003482': 5, '102003178': 5, '102003355': 5, '102017054': 5, '102003393': 4, '102003658': 4, '102003116': 5, '102017195': 2, '102003162': 4, '102003697': 5, '102003256': 4, '102003001': 3, '102016081': 5, '102003137': 5, '102017148': 5, '102003487': 5, '102017139': 3, '102003029': 5, '102003432': 3, '102003177': 5, '102003646': 5, '102003619': 4, '102003171': 5, '102016087': 5, '102016062': 5, '102053022': 4, '102053024': 5, '102003499': 4, '102003367': 3, '102003318': 3, '102017180': 5, '102017104': 2, '102003447': 4, '102003205': 5, '102003425': 5, '102017075': 2, '102017050': 5, '102003083': 5, '102003220': 4, '102183034': 5, '102003018': 5, '102003323': 4, '102003706': 5, '102017010': 5, '102003759': 5, '102003184': 5, '102003661': 5, '102016012': 4, '102016089': 5, '102003039': 5, '102016096': 5, '102003457': 5, '102016083': 5, '102003140': 5, '102053042': 5, '102003017': 5, '102003644': 5, '102016068': 5, '102003042': 3, '102017008': 4, '102003304': 5, '102053007': 4, '102003692': 4, '102017126': 5, '102017069': 3, '102003125': 5, '102003767': 4, '102017171': 5, '102017167': 2, '102016044': 5, '102003673': 4, '102003431': 4, '102003549': 5, '102016075': 5, '102017083': 5, '102003497': 5, '102003494': 5, '102003742': 5, '102017113': 5, '102003105': 4, '102003037': 5, '102003484': 4, '102003655': 5, '102003368': 4, '102003056': 3, '102003493': 5, '102003243': 5, '102003745': 4, '102003157': 5, '102183038': 5, '102053030': 4, '102003424': 5, '102003173': 4, '102003464': 5, '102017112': 5, '102053051': 5, '102003689': 5, '102003403': 5, '102003648': 4, '102003623': 5, '102003622': 4, '102067006': 5, '102003687': 5, '102003512': 4, '102017017': 4, '102003030': 5, '102003071': 5, '102197018': 4, '102017145': 5, '102183040': 4, '102003618': 5, '102053009': 3, '102003665': 5, '102003164': 5, '102017070': 5, '102183035': 5, '102017142': 5, '102003124': 5, '102017184': 5, '102017187': 5, '102017090': 5, '102016109': 5, '102183050': 5, '102053043': 4, '102017137': 3, '102003452': 5, '102016034': 5, '102003427': 4, '102003604': 5, '102003156': 5, '102016105': 4, '102003680': 5, '102197019': 5, '102017089': 2, '102017051': 5, '102003131': 5, '102016090': 5, '102003703': 5, '102003685': 3, '102183048': 5, '102196004': 5, '102003582': 1, '102003541': 5, '102003634': 5, '102003483': 4, '102003560': 5, '102197021': 5, '102003704': 5, '102003070': 4, '102003736': 5, '102003467': 5, '102003373': 5, '102003551': 3, '102003404': 5, '102003718': 5, '102003158': 5, '102017079': 5, '102196010': 4, '102053031': 3, '102017118': 4, '102003772': 4, '102003322': 5, '102017085': 5, '102067011': 5, '102053010': 5, '102197016': 5, '102003242': 4, '102003532': 5, '102003253': 3, '102003485': 4, '102003289': 0, '102017120': 5, '102003402': 4, '102003653': 5, '102003293': 3, '102003580': 5, '102003410': 5, '102003288': 3, '102003712': 5, '102003128': 5, '102016009': 5, '102003251': 3, '102003596': 4, '102017129': 5, '102003468': 2, '102003146': 4, '102017138': 5, '102003559': 5, '102003395': 5, '102017065': 4, '102003380': 5, '102003672': 5, '102003117': 4, '102003050': 4, '102053008': 5, '102003766': 5, '102003139': 4, '102003082': 5, '102003295': 5, '102003053': 5, '102017047': 4, '102017110': 4, '102053005': 4, '102017119': 5, '102017151': 5, '102003465': 5, '102016091': 5, '102017178': 4, '102003768': 4, '102003565': 3, '102053011': 4, '102053035': 4, '102017163': 2, '102017073': 1, '102003396': 1, '102003417': 4, '102003085': 5, '102016066': 5, '102016100': 4, '102003508': 5, '102003406': 2, '102017182': 5, '102003755': 5, '102017172': 5, '102017060': 4, '102016110': 4, '102017150': 4, '102003690': 1, '102003149': 2, '102003089': 1, '102180347': 1}

# **BY IMPORTING PANDAS**

In [32]:
import pandas as pd
df=pd.read_csv('Marks.csv')
print(df.head())

    Roll Num  Marks
0  102003542      1
1  102003640      1
2  102003725      1
3  102003307      1
4  102003458      1

In [33]:
df['Roll Num'].unique()

array([102003542, 102003640, 102003725, 102003307, 102003458, 102003643,
       102017134, 102003207, 102003315, 102003362, 102003135, 102003650,
       102003675, 102003671, 102003374, 102017034, 102003306, 102003141,
       102003592, 102003478, 102017030, 102016114, 102003152, 102017101,
       102003098, 102003633, 102003132, 102066004, 102003466, 102017188,
       102003413, 102016094, 102017190, 102017121, 102003118, 102003681,
       102183051, 102017016, 102003649, 102003448, 102003421, 102017152,
       102053044, 102003169, 102016049, 102017081, 102053017, 102003299,
       102017096, 102003161, 102003109, 102003313, 102003138, 102017078,
       102003445, 102003553, 102017186, 102003527, 102003407, 102017100,
       102003674, 102183047, 102003160, 102003049, 102003701, 102017159,
       102067010, 102003112, 102003522, 102017067, 102003069, 102053019,
       102016060, 102003384, 102017169, 102017043, 102017133, 102183052,
       102003732, 102003562, 102003235, 102003290, 102003746, 102003694,
       102003586, 102003710, 102003439, 102016116, 102003127, 102017084,
       102067004, 102016011, 102017005, 102016099, 102053036, 102003441,
       102003106, 102003129, 102003346, 102003647, 102003274, 102003090,
       102183044, 102003711, 102003624, 102003656, 102017029, 102016082,
       102003238, 102003002, 102003614, 102003459, 102003099, 102003760,
       102017036, 102003312, 102017143, 102016102, 102067009, 102003505,
       102003206, 102003409, 102003738, 102017040, 102003440, 102003688,
       102017122, 102017064, 102067007, 102003041, 102017147, 102003356,
       102003166, 102017074, 102003707, 102003228, 102003366, 102003165,
       102003423, 102053018, 102053032, 102003631, 102003475, 102003663,
       102003716, 102017025, 102003333, 102017191, 102003364, 102003101,
       102017132, 102017059, 102003405, 102003702, 102003257, 102003472,
       102003113, 102053028, 102003628, 102183056, 102003451, 102003578,
       102053013, 102003334, 102053012, 102017024, 102003463, 102017045,
       102017189, 102003482, 102003178, 102003355, 102017054, 102003393,
       102003658, 102003116, 102017195, 102003162, 102003697, 102003256,
       102003001, 102016081, 102003137, 102017148, 102003487, 102017139,
       102003029, 102003432, 102003177, 102003646, 102003619, 102003171,
       102016087, 102016062, 102053022, 102053024, 102003499, 102003367,
       102003318, 102017180, 102017104, 102003447, 102003205, 102003425,
       102017075, 102017050, 102003083, 102003220, 102183034, 102003018,
       102003323, 102003706, 102017010, 102003759, 102003184, 102003661,
       102016012, 102016089, 102003039, 102016096, 102003457, 102016083,
       102003140, 102053042, 102003017, 102003644, 102016068, 102003042,
       102017008, 102003304, 102053007, 102003692, 102017126, 102017069,
       102003125, 102003767, 102017171, 102017167, 102016044, 102003673,
       102003431, 102003549, 102016075, 102017083, 102003497, 102003494,
       102003742, 102017113, 102003105, 102003037, 102003484, 102003655,
       102003368, 102003056, 102003493, 102003243, 102003745, 102003157,
       102183038, 102053030, 102003424, 102003173, 102003464, 102017112,
       102053051, 102003689, 102003403, 102003648, 102003623, 102003622,
       102067006, 102003687, 102003512, 102017017, 102003030, 102003071,
       102197018, 102017145, 102183040, 102003618, 102053009, 102003665,
       102003164, 102017070, 102183035, 102017142, 102003124, 102017184,
       102017187, 102017090, 102016109, 102183050, 102053043, 102017137,
       102003452, 102016034, 102003427, 102003604, 102003156, 102016105,
       102003680, 102197019, 102017089, 102017051, 102003131, 102016090,
       102003703, 102003685, 102183048, 102196004, 102003582, 102003541,
       102003634, 102003483, 102003560, 102197021, 102003704, 102003070,
       102003736, 102003467, 102003373, 102003551, 102003404, 102003718,
       102003158, 102017079, 102196010, 102053031, 102017118, 102003772,
       102003322, 102017085, 102067011, 102053010, 102197016, 102003242,
       102003532, 102003253, 102003485, 102003289, 102017120, 102003402,
       102003653, 102003293, 102003580, 102003410, 102003288, 102003712,
       102003128, 102016009, 102003251, 102003596, 102017129, 102003468,
       102003146, 102017138, 102003559, 102003395, 102017065, 102003380,
       102003672, 102003117, 102003050, 102053008, 102003766, 102003139,
       102003082, 102003295, 102003053, 102017047, 102017110, 102053005,
       102017119, 102017151, 102003465, 102016091, 102017178, 102003768,
       102003565, 102053011, 102053035, 102017163, 102017073, 102003396,
       102003417, 102003085, 102016066, 102016100, 102003508, 102003406,
       102017182, 102003755, 102017172, 102017060, 102016110, 102017150,
       102003690, 102003149, 102003089, 102180347])

In [34]:
roll_nos=list(df['Roll Num'].unique())

In [35]:
output={}
output = df.groupby('Roll Num')['Marks'].sum()
output.head(100)

Roll Num
102003001    3
102003002    5
102003017    5
102003018    5
102003029    5
            ..
102003346    4
102003355    5
102003356    4
102003362    4
102003364    4
Name: Marks, Length: 100, dtype: int64